# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Grammin' do
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

# Pods for Grammin

#Firebase
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'Firebase/Messaging'

#3rd Party Auth
pod 'GoogleSignIn'
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'

#Reveal VC
pod 'PBRevealViewController/Swift'

#Multiple image selection
pod 'QBImagePickerController'

#Font Awesome
pod 'FontAwesome.swift'

end
